CREATE TABLE USERS(
    id_user VARCHAR(30) NOT NULL,
    username VARCHAR(60) NOT NULL,
    email VARCHAR(200) NOT NULL ,
    password VARCHAR(20) NOT NULL
);

ALTER TABLE USERS
    ADD CONSTRAINT USER_PK PRIMARY KEY(id_user);


CREATE TABLE VIDEOS(
    id_video VARCHAR(30) NOT NULL ,
    title VARCHAR(500) NOT NULL ,
    description VARCHAR ,
    url VARCHAR(500) NOT NULL ,
    uploaded_at TIMESTAMP(0) NOT NULL ,
    creator_id VARCHAR(30) NOT NULL
);

ALTER TABLE VIDEOS
    ADD CONSTRAINT VIDEOS_PK PRIMARY KEY(id_video);

ALTER TABLE VIDEOS
    ADD CONSTRAINT VIDEO_USER_FK
        FOREIGN KEY (creator_id) REFERENCES USERS(id_user);

CREATE TABLE COMMENTS(
    id_user VARCHAR(30) NOT NULL ,
    id_video VARCHAR(30) NOT NULL ,
    content VARCHAR NOT NULL,
    created_at TIMESTAMP(0) NOT NULL
);

ALTER TABLE COMMENTS
    ADD CONSTRAINT COMMENT_USER_FK
        FOREIGN KEY(id_user) REFERENCES USERS(id_user);

ALTER TABLE COMMENTS
    ADD CONSTRAINT COMMENT_VIDEO_FK
        FOREIGN KEY(id_video) REFERENCES VIDEOS(id_video);

ALTER TABLE COMMENTS
    ADD CONSTRAINT COMMENT_PK PRIMARY KEY (id_user, id_video);



CREATE TABLE VIEWS(
    id_user VARCHAR(30) NOT NULL ,
    id_video VARCHAR(30) NOT NULL ,
    viewed_at TIMESTAMP(0) NOT NULL
);

ALTER TABLE VIEWS
    ADD CONSTRAINT VIEWS_USER_FK
        FOREIGN KEY(id_user) REFERENCES USERS(id_user);

ALTER TABLE VIEWS
    ADD CONSTRAINT VIEWS_VIDEO_FK
        FOREIGN KEY(id_video) REFERENCES VIDEOS(id_video);

ALTER TABLE VIEWS
    ADD CONSTRAINT COMMENT_PK PRIMARY KEY (id_user, id_video);


CREATE TABLE REACTIONS(
    id_user VARCHAR(30) NOT NULL ,
    id_video VARCHAR(30) NOT NULL ,
    type VARCHAR(10) NOT NULL,
    created_at TIMESTAMP(0) NOT NULL
);

ALTER TABLE REACTIONS
    ADD CONSTRAINT REACTIONS_USER_FK
        FOREIGN KEY(id_user) REFERENCES USERS(id_user);

ALTER TABLE REACTIONS
    ADD CONSTRAINT REACTIONS_VIDEO_FK
        FOREIGN KEY(id_video) REFERENCES VIDEOS(id_video);

ALTER TABLE REACTIONS
    ADD CONSTRAINT CHK_REACTION CHECK (type IN ('LIKE','DISLIKE'));

ALTER TABLE REACTIONS
    ADD CONSTRAINT REACTION_PK PRIMARY KEY (id_user, id_video);



